admin:
  ip: 0.0.0.0
  port: 9990

routers:
- protocol: http
  interpreter:
    kind: io.l5d.namerd.http
    experimental: true
    dst: /$/inet/n5d/4180
  servers:
  - port: 4140
    ip: 0.0.0.0

usage:
  enabled: false
