admin:
  port: 9991

storage:
  kind: io.l5d.zk
  experimental: true
  pathPrefix: /dtabs
  zkAddrs:
  - host: zoo1
    port: 2181

namers:
- kind: io.l5d.fs
  rootDir: /io.buoyant/disco

interfaces:
- kind: io.l5d.httpController
  ip: 0.0.0.0
  port: 4180
